server:
  port: 8081

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:postgresql://localhost:5540/gateway_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gateway-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: verySecretKeyForDeliveryFlowProject2026123456789
  expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html